site_name: 全民瘋AI系列 [經典機器學習]
site_author: 10程式中
# site_url: 
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - javascripts/extra.js
  - javascripts/analytics.js
theme:
  name: material
  language: 'zh-TW'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'brown'
    accent: 'deep orange'
repo_url: https://github.com/andy6804tw/2021-13th-ironman
# use_directory_urls: false
edit_uri: ""
# Copyright
copyright: 'Copyright © 2021 - 2024 10程式中'
nav:
  - '第一部分 AI基礎概念':
    - '1.全民瘋AI系列2.0目標介紹/README.md'
    - '2.快來探索AI的世界/README.md'
    - '3.你真了解資料嗎試試看視覺化分析吧/README.md'
    - '4.咱們一起做資料清理和前處理/README.md'
    - '5.機器學習大補帖/README.md'
  - '第二部分 機器學習入門':
    - '6.非監督式學習k-means分群/README.md'
    - '7.非監督式學習-降維/README.md'
    - '8.線性迴歸/README.md'
    - '9.邏輯迴歸/README.md'
    - '10.KNN/README.md'
    - '11.SVM/README.md'
    - '12.決策樹/README.md'
    - '13.整體學習/README.md'
    - '14.隨機森林/README.md'
    - '15.XGBoost/README.md'
    - '16.Stacking/README.md'
    - '17.LightGBM/README.md'
    - '18.CatBoost/README.md'
  - '第三部分 進階概念與應用':
    - '19.AutoML/README.md'
    - '20.Auto-Sklearn/README.md'
    - '21.Optuna/README.md'
    - '22.Plotly-Express/README.md'
    - '23.資料分布與離群值處理/README.md'
    - '24.不能忽視的過擬合與欠擬合/README.md'
    - '25.交叉驗證 Cross-Validation 簡介/README.md'
    - '26.交叉驗證 K-Fold Cross-Validation/README.md'
    - '27.機器學習常犯錯的十件事/README.md'
    - '28.儲存訓練好的模型/README.md'
    - '29.使用Python-Flask架設API吧/README.md'
    - '30.使用 Heroku 部署機器學習 API/README.md'



markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
plugins:
  - search
  # - mkpdfs:
  #     design: design/report.css
  #     author: Tsai Yi Lin
  #     company: "10程式中"
  #     toc_title: Table of contents
  #     output_path: pdf/全民瘋AI系列_經典機器學習_v2.1.pdf

